# Generated by Django 5.1.1 on 2024-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCBIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('translation_term', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['db', 'query'], name='ncbi_data_n_db_5058ba_idx')],
                'unique_together': {('db', 'query')},
            },
        ),
    ]
